### ISSUE TITLE
Debugging in iOS simulator?

### ISSUE THREAD

**Issue by johnsturgeon** [AnarchyTools/SublimeAnarchyDebug#3]
Is there a way to debug in the iOS Simulator?

**Comment by dunkelstern** [comment]
probably, the only problem would be starting the thing in the simulator, attaching to a manually started process would work though. Honestly I am using Xcode for that currently. If you're using anarchy tools to build you may probably have a look at xcode-emit to create an xcode project for you.

**Comment by johnsturgeon** [comment]
Thank you for getting back to me,

I launch in the sim using:
`xcrun simctl launch booted <app bundle id> | awk '{print $2}' | pbcopy`
then
`lldb -p 'pid'`
Would it be possible to do something like that?  I don't use any of the anarchy tools, I ran across this plugin when looking to see if anybody got a decent lldb sublime text debugger going yet :)

Also, I'm not sure what my project settings would even look like in this instance.

**Comment by drewcrawford** [comment]
Let me do a braindump for you from the compiler side.

`atbuild`, our build tool, doesn't currently emit `.app`s.  The reason is mostly lack of demand I think, since apps (unlike say, frameworks or executables) are more likely to need asset catalogs, IB, and related Xcode technology, and it seems convenient to do that from Xcode rather than reimplement all of it.  That said, if you're interested in cooking up `.app` compilation for `atbuild`, we would take the patch, maybe as a plugin or something.

Now you can instead emit an xcodeproj with `xcode-emit`, or you could maintain a real xcode project separately.  Then you could simply pop an `xcodebuild` incantation on the front of your CLI and debug that way.  I'm not totally sure what that buys you above and beyond just debugging with Xcode, but it sounds like the kind of crazy we might want to support.

Regardless, I think we should at least support attaching to a pid that you launched elsewhere.  Do we not yet support that @dunkelstern ?

**Comment by dunkelstern** [comment]
I am on that and on remote debugging (starting the debug server via ssh + tunneling the port through) but currently lldb is a bit problematic because it can't find debugging symbols or source then. If you compile with inline Dwarf symbols it should be doable, dsym not so much as there is a lot of magic involved with that (for example: Xcode uses spotlight to find the right dsym file with the correct uuid etc.)
